version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carpool_db
    ports:

      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_DSN=host=db user=user password=password dbname=carpool_db port=5432 sslmode=disable


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app       
      - /app/node_modules      
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://127.0.0.1:8000


  bot:
    build: ./telegram_bot
    depends_on:
      - backend
    environment:
      - BOT_TOKEN=8694496064:AAHVkK2eZlZ9XyXtHFsLKJVGd1-UZXn-EgM
      - API_URL=http://backend:8000/api
      - WEBAPP_URL=http://127.0.0.1:5173
      - BOT_PROXY=socks5://VJGaWa:m1UBZ7@23.236.138.5:9240

volumes:
  postgres_data: